services:
  file-translation-service:
    build:
      context: ./
      dockerfile: ./FileTranslationService/Dockerfile
      args:
        CONFIGURATION: $CONFIGURATION
    ports:
      - "5001:80"
    env_file:
      - .env
    environment:
      Services__TranslationSystem__Url: $Services__TranslationSystem__Url
      Services__FileTranslation__UserName: $Services__FileTranslation__UserName
      Services__FileTranslation__Password: $Services__FileTranslation__Password
      Services__Database__ConnectionString: $Services__Database__ConnectionString
      Services__RabbitMQ__Host: $Services__RabbitMQ__Host
      Services__RabbitMQ__UserName: $Services__RabbitMQ__UserName
      Services__RabbitMQ__Password: $Services__RabbitMQ__Password
      Configuration__FileSystemStoragePath: $Configuration__FileSystemStoragePath
      Configuration__UserGroupMetadataExpiration____default__: $Configuration__UserGroupMetadataExpiration____default__